// Ol3-Google-Maps. See https://github.com/mapgears/ol3-google-maps/
// License: https://github.com/mapgears/ol3-google-maps/blob/master/LICENSE
// Version: v0.2-4-g4fb95e6

(function(){var h,l=this;
function n(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function aa(a,b,c){return a.call.apply(a.bind,arguments)}function ba(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}
function p(a,b,c){p=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?aa:ba;return p.apply(null,arguments)}function q(a,b){var c=a.split("."),d=l;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d[e]?d=d[e]:d=d[e]={}:d[e]=b}function s(a,b){function c(){}c.prototype=b.prototype;a.i=b.prototype;a.prototype=new c;a.aa=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};function t(a,b){this.c=a;this.a=b};function u(a,b){return a<b?-1:a>b?1:0};var v=Array.prototype,ca=v.indexOf?function(a,b,c){return v.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if("string"==typeof a)return"string"==typeof b&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};var y;a:{var z=l.navigator;if(z){var A=z.userAgent;if(A){y=A;break a}}y=""};var B=-1!=y.indexOf("Opera")||-1!=y.indexOf("OPR"),C=-1!=y.indexOf("Trident")||-1!=y.indexOf("MSIE"),D=-1!=y.indexOf("Gecko")&&-1==y.toLowerCase().indexOf("webkit")&&!(-1!=y.indexOf("Trident")||-1!=y.indexOf("MSIE")),E=-1!=y.toLowerCase().indexOf("webkit");function F(){var a=l.document;return a?a.documentMode:void 0}
var G=function(){var a="",b;if(B&&l.opera)return a=l.opera.version,"function"==n(a)?a():a;D?b=/rv\:([^\);]+)(\)|;)/:C?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:E&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(y))?a[1]:"");return C&&(b=F(),b>parseFloat(a))?String(b):a}(),da={};
function H(a){var b;if(!(b=da[a])){b=0;for(var c=String(G).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",k=d[f]||"",w=RegExp("(\\d*)(\\D*)","g"),m=RegExp("(\\d*)(\\D*)","g");do{var r=w.exec(g)||["","",""],x=m.exec(k)||["","",""];if(0==r[0].length&&0==x[0].length)break;b=u(0==r[1].length?0:parseInt(r[1],10),0==x[1].length?0:parseInt(x[1],10))||u(0==r[2].length,0==x[2].length)||
u(r[2],x[2])}while(0==b)}b=da[a]=0<=b}return b}var ea=l.document,fa=ea&&C?F()||("CSS1Compat"==ea.compatMode?parseInt(G,10):5):void 0;var I;(I=!C)||(I=C&&9<=fa);var ga=I,ha=C&&!H("9");!E||H("528");D&&H("1.9b")||C&&H("8")||B&&H("9.5")||E&&H("528");D&&!H("8")||C&&H("9");function J(a,b){this.type=a;this.a=this.c=b}J.prototype.b=function(){};function K(a){K[" "](a);return a}K[" "]=function(){};function L(a,b){J.call(this,a?a.type:"");this.d=this.a=this.c=null;if(a){this.type=a.type;this.c=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;if(c&&D)try{K(c.nodeName)}catch(d){}this.d=a;a.defaultPrevented&&this.b()}}s(L,J);L.prototype.b=function(){L.i.b.call(this);var a=this.d;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,ha)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var ia="closure_listenable_"+(1E6*Math.random()|0),ja=0;function ka(a,b,c,d,e){this.o=a;this.a=null;this.src=b;this.type=c;this.A=!!d;this.c=e;++ja;this.r=this.w=!1}function la(a){a.r=!0;a.o=null;a.a=null;a.src=null;a.c=null};function ma(a){this.src=a;this.a={};this.c=0};var M="closure_lm_"+(1E6*Math.random()|0),N={},na=0;
function oa(a,b,c,d,e){if("array"==n(b)){for(var f=0;f<b.length;f++)oa(a,b[f],c,d,e);return null}c=pa(c);if(a&&a[ia])a=a.a(b,c,d,e);else{f=c;if(!b)throw Error("Invalid event type");c=!!d;var g=O(a);g||(a[M]=g=new ma(a));var k=g,w=b.toString(),g=k.a[w];g||(g=k.a[w]=[],k.c++);var m;b:{for(m=0;m<g.length;++m){var r=g[m];if(!r.r&&r.o==f&&r.A==!!d&&r.c==e)break b}m=-1}-1<m?(d=g[m],d.w=!1):(d=new ka(f,k.src,w,!!d,e),d.w=!1,g.push(d));d.a||(e=qa(),d.a=e,e.src=a,e.o=d,a.addEventListener?a.addEventListener(b.toString(),
e,c):a.attachEvent(ra(b.toString()),e),na++);a=d}return a}function qa(){var a=sa,b=ga?function(c){return a.call(b.src,b.o,c)}:function(c){c=a.call(b.src,b.o,c);if(!c)return c};return b}function ra(a){return a in N?N[a]:N[a]="on"+a}function ta(a,b,c,d){var e=1;if(a=O(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.A==c&&!f.r&&(e&=!1!==ua(f,d))}return Boolean(e)}
function ua(a,b){var c=a.o,d=a.c||a.src;if(a.w&&"number"!=typeof a&&a&&!a.r){var e=a.src;if(e&&e[ia])e.ba(a);else{var f=a.type,g=a.a;e.removeEventListener?e.removeEventListener(f,g,a.A):e.detachEvent&&e.detachEvent(ra(f),g);na--;if(f=O(e)){g=a.type;if(g in f.a){var k=f.a[g],w=ca(k,a),m;(m=0<=w)&&v.splice.call(k,w,1);m&&(la(a),0==f.a[g].length&&(delete f.a[g],f.c--))}0==f.c&&(f.src=null,e[M]=null)}else la(a)}}return c.call(d,b)}
function sa(a,b){if(a.r)return!0;if(!ga){var c;if(!(c=b))a:{c=["window","event"];for(var d=l,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new L(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,k=e.length-1;0<=k;k--)c.a=e[k],d&=ta(e[k],f,!0,c);for(k=0;k<e.length;k++)c.a=e[k],d&=ta(e[k],f,!1,c)}return d}return ua(a,
new L(b,this))}function O(a){a=a[M];return a instanceof ma?a:null}var va="__closure_events_fn_"+(1E9*Math.random()>>>0);function pa(a){return"function"==n(a)?a:a[va]||(a[va]=function(b){return a.handleEvent(b)})};var wa=[156543.03390625,78271.516953125,39135.7584765625,19567.87923828125,9783.939619140625,4891.9698095703125,2445.9849047851562,1222.9924523925781,611.4962261962891,305.74811309814453,152.87405654907226,76.43702827453613,38.218514137268066,19.109257068634033,9.554628534317017,4.777314267158508,2.388657133579254,1.194328566789627,.5971642833948135,.298582141697,.14929107084,.07464553542,.03732276771];
function xa(a){var b=null;return b=a instanceof ol.geom.Point?a.getCoordinates():a instanceof ol.geom.Polygon?a.getInteriorPoint().getCoordinates():ol.extent.getCenter(a.getExtent())}function P(a){var b="",c=null;"string"===typeof a?0===a.indexOf("rgba")?c=ya(a):b=a:c=a;null!==c&&(b=["rgb(",c[0],",",c[1],",",c[2],")"].join(""));return b}function Q(a){var b=null,c=null;"string"===typeof a?0===a.indexOf("rgba")&&(c=ya(a)):c=a;c&&void 0!==c[3]&&(b=+c[3]);return b}
function za(a){var b=null;a instanceof ol.style.Style?b=a:a instanceof ol.layer.Vector||a instanceof ol.Feature?(b=a.getStyle())&&b instanceof Function&&(b=b()[0]):a instanceof Function&&(b=a()[0]);return b}function ya(a){var b=null;(a=a.match(/^rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*(\d+(?:\.\d+)?))?\)$/))&&a.length&&(b=[+a[1],+a[2],+a[3],+a[4]]);return b}function R(a){a.forEach(ol.Observable.unByKey);a.length=0};function S(a){this.set("font","normal 10px sans-serif");this.set("textAlign","center");this.set("textBaseline","middle");this.set("zIndex",1E3);this.setValues(a)}s(S,google.maps.OverlayView);h=S.prototype;h.G=!1;h.I=0;h.Q=0;h.changed=function(a){switch(a){case "fontColor":case "fontFamily":case "fontSize":case "fontWeight":case "strokeColor":case "strokeWeight":case "text":case "textAlign":case "textBaseline":Aa(this);break;case "maxZoom":case "minZoom":case "offsetX":case "offsetY":case "position":this.draw()}};
function Aa(a){var b=a.a;if(b){var c=b.style,d=a.get("fontColor");if(d&&(c.zIndex=a.get("zIndex"),c=b.getContext("2d"),c.clearRect(0,0,b.width,b.height),c.textBaseline=a.get("textBaseline"),c.strokeStyle=a.get("strokeColor"),c.fillStyle=d,c.font=a.get("font"),c.textAlign=a.get("textAlign"),d=a.get("text"))){var e=b.width/2,b=b.height/2;if(a=Number(a.get("strokeWeight")))c.lineWidth=a,c.strokeText(d,e,b);c.fillText(d,e,b)}}}
h.onAdd=function(){var a=this.a=document.createElement("canvas");a.style.position="absolute";a.getContext("2d").lineJoin="round";Aa(this);var b=this.getPanes();b&&b.markerLayer.appendChild(a)};h.draw=function(){if(this.G)Ba(this);else{var a=this.a;if(a){var a=a.getContext("2d"),b=a.canvas.height;this.Q=a.canvas.width;this.I=b;Ba(this)&&(this.G=!0)}}};
function Ba(a){var b=a.get("position");if(!b)return!1;var c=a.getProjection();if(!c)return!1;var c=c.fromLatLngToDivPixel(b),d=a.I,e=a.Q,f=a.get("offsetX")||0,g=a.get("offsetY")||0,b=a.a.style;b.top=c.y-d/2+g+"px";b.left=c.x-e/2+f+"px";c=a.get("minZoom");d=a.get("maxZoom");void 0===c&&void 0===d?a="":(a=a.getMap())?(a=a.getZoom(),a=a<c||a>d?"hidden":""):a="";b.visibility=a;return!0}h.onRemove=function(){var a=this.a;a&&a.parentNode&&a.parentNode.removeChild(a)};function Ca(a,b){var c=null;if(a instanceof ol.geom.Point)c=T(a,b);else if(a instanceof ol.geom.LineString||a instanceof ol.geom.Polygon){var d=void 0!==b?b.getView().getProjection():"EPSG:3857",c=[],e,f;f=a instanceof ol.geom.LineString?a.getCoordinates():a.getCoordinates()[0];for(var g=0,k=f.length;g<k;g++)e=ol.proj.transform(f[g],d,"EPSG:4326"),c.push(new google.maps.LatLng(e[1],e[0]));d=null;a instanceof ol.geom.LineString?d=new google.maps.Data.LineString(c):d=new google.maps.Data.Polygon([c]);
c=d}return c}function T(a,b){var c=void 0!==b?b.getView().getProjection():"EPSG:3857",d;d=a instanceof ol.geom.Point?a.getCoordinates():a;c=ol.proj.transform(d,c,"EPSG:4326");return new google.maps.LatLng(c[1],c[0])}
function Da(a,b){var c=null,d=za(a);if(d){var c={},e=d.getStroke();if(e){var f=e.getColor();f&&(c.strokeColor=P(f),f=Q(f),null!==f&&(c.strokeOpacity=f));(e=e.getWidth())&&(c.strokeWeight=e)}if(e=d.getFill())if(e=e.getColor())c.fillColor=P(e),e=Q(e),null!==e&&(c.fillOpacity=e);if(f=d.getImage()){d={};e={};if(f instanceof ol.style.Circle){e.path=google.maps.SymbolPath.CIRCLE;var g=f.getStroke();if(g){var k=g.getColor();k&&(e.strokeColor=P(k));e.strokeWeight=g.getWidth()}if(g=f.getFill())if(g=g.getColor())e.fillColor=
P(g),g=Q(g),e.fillOpacity=null!==g?g:1;(f=f.getRadius())&&(e.scale=f)}else f instanceof ol.style.Icon&&((g=f.getSrc())&&(e.url=g),g=f.getScale(),(k=f.getAnchor())&&(e.anchor=void 0!==g?new google.maps.Point(k[0]*g,k[1]*g):new google.maps.Point(k[0],k[1])),(k=f.getOrigin())&&(e.origin=new google.maps.Point(k[0],k[1])),f=f.getSize())&&(e.size=new google.maps.Size(f[0],f[1]),void 0!==g&&(e.scaledSize=new google.maps.Size(f[0]*g,f[1]*g)));Object.keys(d).length?c.icon=d:Object.keys(e).length&&(c.icon=
e)}0===Object.keys(c).length?c.visible=!1:void 0!==b&&(c.zIndex=2*b)}return c};function U(a,b){this.h=[];t.call(this,a,b)}s(U,t);U.prototype.f=function(){};U.prototype.e=function(){R(this.h)};function V(a,b,c,d,e){this.b=c;this.d=d;this.g=e;U.call(this,a,b)}s(V,U);h=V.prototype;h.l=null;h.j=null;
h.f=function(){V.i.f.call(this);var a=this.b.getGeometry(),b=this.b.getGeometry(),b=Ca(b,void 0);this.l=new google.maps.Data.Feature({geometry:b});this.d.add(this.l);(b=Da(this.b,this.g))&&this.d.overrideStyle(this.l,b);if(b=za(this.b)){var c=b.getText();if(c){var b={align:"center",position:T(xa(a)),zIndex:2*this.g+1},d=c.getText();d&&(b.text=d);(d=c.getFont())&&(b.font=d);(d=c.getFill())&&(d=d.getColor())&&(b.fontColor=d);if(d=c.getStroke()){var e=d.getColor();e&&(b.strokeColor=e);(d=d.getWidth())&&
(b.strokeWeight=d)}(d=c.getOffsetX())&&(b.offsetX=d);(d=c.getOffsetY())&&(b.offsetY=d);(d=c.getTextAlign())&&(b.textAlign=d);(c=c.getTextBaseline())&&(b.textBaseline=c);this.j=new S(b);this.j.setMap(this.a)}}this.h.push(a.on("change",this.S,this))};h.e=function(){this.d.remove(this.l);this.l=null;this.j&&(this.j.setMap(null),this.j=null);V.i.e.call(this)};h.S=function(){var a=this.b.getGeometry();this.l.setGeometry(Ca(a));this.j&&(a=T(xa(a)),this.j.set("position",a))};function W(a,b,c,d){this.b=[];this.g=[];this.p=d;this.d=c;U.call(this,a,b)}s(W,U);h=W.prototype;h.f=function(){W.i.f.call(this);this.d.getFeatures().forEach(this.O,this);var a=this.h;a.push(this.d.on("addfeature",this.R,this));a.push(this.d.on("removefeature",this.V,this))};h.e=function(){this.d.getFeatures().forEach(this.M,this);W.i.e.call(this)};h.R=function(a){this.O(a.feature)};h.V=function(a){this.M(a.feature)};
h.O=function(a){var b=this.c,c=this.a,d=this.p;this.b.push(a);b=new V(b,c,a,d,this.b.indexOf(a));b.f();this.g.push({feature:a,q:b})};h.M=function(a){a=this.b.indexOf(a);-1!==a&&(this.b.splice(a,1),this.g[a].q.e(),this.g.splice(a,1))};function X(a,b){U.call(this,a,b)}s(X,U);h=X.prototype;h.u=null;h.f=function(){X.i.f.call(this);var a=this.c.getView(),b=this.h;b.push(a.on("change:center",this.t,this));b.push(a.on("change:resolution",this.C,this));b.push(oa(window,"resize",this.X,!1,this));this.t();this.C()};h.e=function(){X.i.e.call(this)};h.t=function(){var a=this.c.getView(),b=a.getProjection(),a=a.getCenter();"array"==n(a)&&(a=ol.proj.transform(a,b,"EPSG:4326"),this.a.setCenter(new google.maps.LatLng(a[1],a[0])))};
h.C=function(){var a=this.c.getView().getResolution();if("number"==typeof a){var b;b=null;for(var a=Math.round(1E3*a)/1E3,c=0,d=wa.length;c<d;c++)if(a==Math.round(1E3*wa[c])/1E3){b=c;break}null!==b&&this.a.setZoom(b)}};h.X=function(){null===this.u||l.clearTimeout(this.u);this.u=window.setTimeout(p(this.$,this),100)};h.$=function(){this.t();this.u=null};function Y(a){a=void 0!==a?a:{};ol.layer.Group.call(this,a);this.a=void 0!==a.mapTypeId?a.mapTypeId:google.maps.MapTypeId.ROADMAP;this.c=a.styles?a.styles:null}s(Y,ol.layer.Group);function Z(a,b){this.s=[];this.p=[];this.b=[];this.B=[];this.g=new X(a,b);this.H=b.getDiv();this.d=a.getViewport();this.J=a.getTargetElement();U.call(this,a,b)}s(Z,U);h=Z.prototype;h.n=!1;h.f=function(){Z.i.f.call(this);var a=this.c.getLayers();a.forEach(this.P,this);var b=this.h;b.push(a.on("add",this.T,this));b.push(a.on("remove",this.U,this))};h.e=function(){this.c.getLayers().forEach(this.N,this);Z.i.e.call(this)};h.T=function(a){this.P(a.element)};h.U=function(a){this.N(a.element)};
h.P=function(a){if(a instanceof Y)this.s.push(a),this.p.push({layer:a,h:[a.on("change:visible",this.D,this)]}),this.D();else if(a instanceof ol.layer.Vector){var b=this.c,c=this.a,d=a.getSource();if(d){this.B.push(a);var e=new google.maps.Data({map:c}),f=Da(a);f&&e.setStyle(f);b=new W(b,c,d,e);c=a.getOpacity();e={data:e,q:b,layer:a,h:[],opacity:c};e.h.push(a.on("change:visible",this.W.bind(this,e),this));this.n&&this.v(e);this.b.push(e)}}};
h.N=function(a){if(a instanceof Y)a=this.s.indexOf(a),-1!==a&&(this.s.splice(a,1),R(this.p[a].h),this.p.splice(a,1),this.D());else if(a instanceof ol.layer.Vector){var b=this.B.indexOf(a);if(-1!==b){this.B.splice(b,1);var c=this.b[b];R(c.h);c.data.setMap(null);c.q.e();a.setOpacity(c.opacity);this.b.splice(b,1)}}};
h.D=function(){var a=null;this.c.getLayers().getArray().slice(0).reverse().every(function(b){return b instanceof Y&&b.getVisible()&&-1!==this.s.indexOf(b)?(a=b,!1):!0},this);if(a){this.a.setMapTypeId(a.a);var b=a.c;b?this.a.setOptions({styles:b}):this.a.setOptions({styles:null});this.n||(this.J.appendChild(this.H),this.d.remove(),this.a.controls[google.maps.ControlPosition.TOP_LEFT].push(this.d),this.g.f(),google.maps.event.trigger(this.a,"resize"),this.g.t(),this.g.C(),this.b.forEach(this.v,this),
this.n=!0)}else this.n&&(this.a.controls[google.maps.ControlPosition.TOP_LEFT].removeAt(0),this.J.appendChild(this.d),this.H.remove(),this.g.e(),this.d.style.position="relative",this.b.forEach(this.F,this),this.n=!1)};h.v=function(a){a.layer.getVisible()&&(a.q.f(),a.layer.setOpacity(0))};h.F=function(a){a.q.e();a.layer.setOpacity(a.opacity)};h.W=function(a){a.layer.getVisible()?this.v(a):this.F(a)};function $(a){this.b=[];var b=document.createElement("div");b.style.height="inherit";b.style.width="inherit";b=new google.maps.Map(b,{disableDefaultUI:!0,disableDoubleClickZoom:!0,draggable:!1,keyboardShortcuts:!1,mapTypeId:google.maps.MapTypeId.ROADMAP,scrollwheel:!1,streetViewControl:!1});t.call(this,a.map,b);this.d=new Z(this.c,this.a);this.b.push(this.d)}s($,t);h=$.prototype;h.k=!1;h.K=function(){if(!this.k){for(var a=0,b=this.b.length;a<b;a++)this.b[a].f();this.k=!0}};
h.L=function(){if(this.k){for(var a=0,b=this.b.length;a<b;a++)this.b[a].e();this.k=!1}};h.Y=function(){return this.k&&this.d.n};h.Z=function(){this.k?this.L():this.K()};q("olgm.OLGoogleMaps",$);$.prototype.activate=$.prototype.K;$.prototype.deactivate=$.prototype.L;$.prototype.getGoogleMapsActive=$.prototype.Y;$.prototype.toggle=$.prototype.Z;q("olgm.layer.Google",Y);q("olgm.interaction.defaults",function(a){a=void 0!==a?a:{};a.altShiftDragRotate=!1;a.dragPan=!1;a.pinchRotate=!1;return ol.interaction.defaults(a).extend([new ol.interaction.DragPan])});q("olgm.gm.MapLabel",S);S.prototype.changed=S.prototype.changed;S.prototype.onAdd=S.prototype.onAdd;
S.prototype.draw=S.prototype.draw;S.prototype.onRemove=S.prototype.onRemove;})();
